import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import ContextComponents from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CCB Thailand Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {
  return (
    <html lang="en">
      <body>
        <MobileLayout>
          <ContextComponents>{children}</ContextComponents>
        </MobileLayout>
      </body>
    </html>
  );
}

function MobileLayout({ children }: { children: React.JSX.Element }) {
  return (
    <div className="w-screen flex justify-center bg-black">
      <div className="max-[500px]:w-full w-[500px] min-h-screen">{children}</div>
    </div>
  );
}
